<?php

namespace SuperV\Modules\Hosting\Domains\Package\Model;

use SuperV\Platform\Domains\Entry\EntryModel;
use SuperV\Platform\Domains\Entry\EntryObserver;

class PartObserver extends EntryObserver
{
    public function deleted(EntryModel $entry)
    {
        /** @var PartModel $entry */
        $entry->getDrop()->delete();

        $entry->getRelated()->delete();

        parent::deleted($entry); // TODO: Change the autogenerated stub
    }
}